application:
  name: ApiGateway
server:
  port: 8082

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

api-core:
  ribbon:
    listOfServers: api-realestate.sandbox.navent.biz